export const IPC_CHANNELS = {
  PTY_SPAWN: 'pty:spawn',
  PTY_WRITE: 'pty:write',
  PTY_RESIZE: 'pty:resize',
  PTY_KILL: 'pty:kill',
  PTY_DATA: 'pty:data',
  AGENT_SPAWN: 'agent:spawn',
  AGENT_KILL: 'agent:kill',
  AGENT_LIST: 'agent:list',
  AGENT_STATUS: 'agent:status',
  AGENT_EXIT: 'agent:exit',
  SESSION_LIST: 'session:list',
  SESSION_GET: 'session:get',
  STATE_SAVE: 'state:save',
  STATE_LOAD: 'state:load',
  PROJECT_LIST: 'project:list',
  PROJECT_CREATE: 'project:create',
  PROJECT_REMOVE: 'project:remove',
  PROJECT_UPDATE: 'project:update',
  PROJECT_PICK_DIR: 'project:pick-dir',
  PROJECT_STATE_LOAD: 'project:state:load',
  PROJECT_STATE_SAVE: 'project:state:save',
  NOTIFY: 'notify:show',
  NOTIFY_SET_ENABLED: 'notify:set-enabled',
  FILE_LIST_DIR: 'file:list-dir',
  FILE_READ: 'file:read',
  VOICE_TRANSCRIBE: 'voice:transcribe',
  KEYBINDINGS_LOAD: 'keybindings:load',
  KEYBINDINGS_SAVE: 'keybindings:save',
  SETTINGS_LOAD: 'settings:load',
  SETTINGS_SAVE: 'settings:save',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  WINDOW_ZOOM_IN: 'window:zoom-in',
  WINDOW_ZOOM_OUT: 'window:zoom-out',
  WINDOW_ZOOM_RESET: 'window:zoom-reset',
} as const;

export const FRAME_COALESCE_MS = 16;
export const DEFAULT_SCROLLBACK = 10_000;
export const DEFAULT_COLS = 120;
export const DEFAULT_ROWS = 30;
